### ISSUE TITLE
Add source files

### ISSUE THREAD

**Issue by eliheuer** [w3f/unbounded#1]
There are no source files ([UFO](https://unifiedfontobject.org/), [glyphs](https://glyphsapp.com/), etc) in this Git repository, only compiled fonts, but the about section says the project is open source.

See section 2 of the [Open Source Definition](https://opensource.org/osd)

> The program must include source code, and must allow distribution in source code as well as compiled form. Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code for no more than a reasonable reproduction cost, preferably downloading via the Internet without charge. The source code must be the preferred form in which a programmer would modify the program. Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed.

https://en.wikipedia.org/wiki/The_Open_Source_Definition

**Comment by rmnprkrl** [comment]
Fixes https://github.com/w3f/unbounded/pull/4. Thanks. The source was on the way from the source.
