### ISSUE TITLE
Clarify what “on-chain funded” means in the README?

### ISSUE THREAD

**Issue by eliheuer** [w3f/unbounded#2]
I'm not sure what on-chain funded means, could that be clarified in the main README?

Type designer [Fredrick Brennan](https://en.wikipedia.org/wiki/Fredrick_Brennan) had a Mt. Gox account and makes open source fonts, would his fonts be considered on-chain funded?

I also released an open source font that was funded by an Ethereum NFT sale earlier this year: https://zora.co/collections/0xb013e4f218760bb72f63f8d78a82b546c91897ef
https://gtl.world/001

**Comment by nuke-web3** [comment]
https://polkadot.subscan.io/account/16hZ5DSyXsZV8rSCCz2JTQDrQspbvMLBVL7U1BH6m3WdAgb6 was funded via treasury proposal for this work, I think these are the funding proposals:
- https://polkadot.polkassembly.io/post/958 executed successfully in https://polkadot.polkassembly.io/motion/176
- https://polkadot.polkassembly.io/post/1117 think this didn't move forward.

**Comment by eliheuer** [comment]
Thanks! this is me funding my font on-chain: https://etherscan.io/tx/0xe8d19451e0df16b9476031e10d29a6095e01fb69670d5813b81645e7272600e6

So I guess you beat me to it.
