### ISSUE TITLE
Add Unbounded to Google Fonts

### ISSUE THREAD

**Issue by nuke-web3** [w3f/unbounded#7]
I would quite like to use this font natively in google products, and give this font quite a bit more mainstream adoption via being listed there in those applications. 

https://googlefonts.github.io/gf-guide/onboarding.html shows how, and the requirements are filled  by the font IIUC, so just needs to be added formally.

**Comment by NaN-xyz** [comment]
We've been working on this since initial launch.

As of today: https://fonts.google.com/?query=unbounded

Huge thank you to the GoogleFonts team.

**Comment by nuke-web3** [comment]
https://fonts.google.com/specimen/Unbounded

Congrats!
